// Code generated by mockery v2.8.0. DO NOT EDIT.

package test

import mock "github.com/stretchr/testify/mock"

// MockWorker is an autogenerated mock type for the Worker type
type MockWorker struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *MockWorker) Run() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *MockWorker) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
